### ISSUE TITLE
Filter Fields documentation is wrong/incomplete

### ISSUE THREAD

**Issue by AdamDavis321** [thedges/PSTimeline#2]
In the Filter Fields documentation you explain that you can provide advanced options with a JSON-like syntax. In an example you appended |{'wildcard':'true'} to a field API name to add wildcard capability. Unfortunately when I tried that using the Lightning App Builder it didn't work; I needed to switch it the apostrophes to quotes (|{"wildcard":"true"}) to get it to work.

This may be a function of the Lightning App Builder, so adding a simple note to the documentation may be enough.

**Comment by thedges** [comment]
Thanks Adam. Documentation updated.
